[versions]
kotlin = "2.3.0"
shadow = "9.3.1"
ideaExt = "1.3"
annotations = "24.1.0"
gson = "2.10.1"

[libraries]
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "ideaExt" }
